Repository ATOAPaymentsLimited/atoa-flutter-packages, pull requests merged in 2024-10, with the labels that each got.

#120 feat: flutter upgrade
  .github/workflows/dry_run_regal_publish.yaml
  .github/workflows/publish_regal.yaml
  packages/regal/.fvmrc
  packages/regal/CHANGELOG.md
  packages/regal/example/android/build.gradle
  packages/regal/example/pubspec.lock
  packages/regal/lib/src/theme/theme_data.dart
  packages/regal/lib/src/theme/theme_extension.dart
  packages/regal/lib/src/widgets/regal_button.dart
  packages/regal/lib/src/widgets/regal_date_picker.dart
  packages/regal/pubspec.lock
  packages/regal/pubspec.yaml
Labels: EM Sprint 5

#124 Feature/figtree
  .DS_Store
  packages/.DS_Store
  packages/regal/.DS_Store
  packages/regal/.gitignore
  packages/regal/CHANGELOG.md
  packages/regal/assets/fonts/FigTree/Figtree-Italic-VariableFont_wght.ttf
  packages/regal/assets/fonts/FigTree/Figtree-VariableFont_wght.ttf
  packages/regal/example/pubspec.lock
  packages/regal/lib/src/theme/text/figtree_text_theme.dart
  packages/regal/lib/src/theme/text/text.dart
  packages/regal/lib/src/utils/text_style_extension.dart
  packages/regal/pubspec.lock
  packages/regal/pubspec.yaml
Labels: enhancement

#129 pub: version update
  packages/face_detector_view/pubspec.yaml
Labels: Dependencies

#130 pub: version update
  packages/face_detector_view/pubspec.yaml
Labels: Dependencies
